api/urls.py
from django.urls import path, include
from .models import DepartmentResource, EmployeeResource, TeamResource
from tastypie.api import Api

api = Api(api_name="v1")
d_resource = DepartmentResource()
e_resource = EmployeeResource()
t_resource = TeamResource()
api.register(d_resource)
api.register(e_resource)
api.register(t_resource)

urlpatterns = [
    path("", include(api.urls), name="index")  
]

base/urls.py
# base/urls.py

from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import set_language

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('set-language/', set_language, name='set_language'),
]

urlpatterns += i18n_patterns(
    path("", include("employees.urls")),
    path("api/", include("api.urls"))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

employees/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
     path('', views.index, name="index"),
     path('about/', views.about, name="about"),
     path("contact/", views.contact, name="contact"),
     path('employees/', views.employees, name="employees"),
     path('employees/<int:employee_id>',
          views.single_employee, name="single_employee"),
     path('about/<int:member_id>', 
          views.single_member, name="single_member"),         
          path('change_lang/', views.change_lang, name='change_lang')
]

api/models.py
from tastypie.resources import ModelResource
from employees.models import Department, Employee, Team
from tastypie.authorization import Authorization
from .auth import CustomAuthentication


class DepartmentResource(ModelResource):
    class Meta:
        queryset = Department.objects.all()
        resource_name = "departments"
        allowed_methods = ["get"]


class EmployeeResource(ModelResource):
    class Meta:
        queryset = Employee.objects.all()
        resource_name = "employees"
        allowed_methods = ["get", "post", "delete"]
        authentication = CustomAuthentication()
        authorization = Authorization()
        excludes = ["contract_exp", "created_at"]

    def hydrate(self, bundle):
        bundle.obj.department_id = bundle.data["department_id"]
        return bundle
        
    def dehydrate(self, bundle):
        bundle.data["department_id"] = bundle.obj.department_id
        bundle.data["department"] = bundle.obj.department
        return bundle
        
    def dehydrate_email(self, bundle):
        return bundle.data["email"].upper()       


class TeamResource(ModelResource):
    class Meta:
        queryset = Team.objects.all()
        resource_name = "team"
        allowed_methods = ["get"]

employees/models.py
from django.db import models
from django.utils import timezone


class Department(models.Model):
    title=models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
         verbose_name = "department"
         verbose_name_plural = "departments"


class Employee(models.Model):
    first_name =models.CharField(max_length=55)
    last_name =models.CharField(max_length=55)
    email =models.EmailField(max_length=255)
    is_married =models.BooleanField(default=False)
    salary =models.FloatField(default=0.0)
    contract_exp = models.DateTimeField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.first_name} {self.last_name} | {self.department}"

    class Meta:
        verbose_name = "employee"
        verbose_name_plural = "employees"


class About(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "about"
        verbose_name_plural = "abouts"


class Contact(models.Model):
    address = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.address} | {self.email} | {self.phone}"

    class Meta:
        verbose_name = "contact"
        verbose_name_plural = "contacts"


class Team(models.Model):
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    position = models.CharField(max_length=55)
    about = models.TextField(max_length=255)
    avatar = models.ImageField(
        upload_to= "team")

    def __str__(self):
        return f"{self.first_name} {self.last_name} | {self.position}"

    class Meta:
        verbose_name = "team"
        verbose_name_plural = "teams"


class Slider(models.Model):
    img = models.ImageField(upload_to="slider")
    title = models.CharField(max_length=255)
    descr = models.TextField(max_length=400)
    link = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "slider"
        verbose_name_plural = "sliders"


class SEO(models.Model):
    tag = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=500)
    keywords = models.CharField(max_length=255)
    robots = models.CharField(max_length=255)
    content_type = models.CharField(max_length=255)
    language = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.tag}"

    class Meta:
        verbose_name = "seo"
        verbose_name_plural = "seo"


class OG(models.Model):
    tag = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=500)
    type = models.CharField(max_length=255)
    image = models.ImageField(upload_to="og")
    url = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.tag}"

    class Meta:
        verbose_name = "Open Graph"
        verbose_name_plural = "Open Graphs"

api/views.py
from django.shortcuts import render

# Create your views here.

employees/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.utils.translation import activate, get_language
from django.utils import translation
from django.views.decorators.http import require_POST
from .models import (
    Department, 
    Employee, 
    About, 
    Contact, 
    Team, 
    Slider,
    SEO,
    OG
    )


def index(request):
    slides = Slider.objects.all()
    seo = SEO.objects.filter(tag="home")
    og = OG.objects.filter(tag="home")

    return render(request, "home.html", {
        "slides": slides,
        "seo": seo,
        "og": og,
        #request": request
        })

def employees(request):
    employees = Employee.objects.all()
    seo = SEO.objects.filter(tag="employees")
    og = OG.objects.filter(tag="employees")
    return render(request, "employees.html", {
        "employees": employees, 
        "seo": seo,
        "og": og
    })

def about(request):
    about_text = About.objects.all()
    team = Team.objects.all()
    seo = SEO.objects.filter(tag="about")
    og = OG.objects.filter(tag="about")
    return render(request, "about.html", {
        "about_text": about_text,
        "team": team,
        "seo": seo,
        "og": og
    })

def contact(request):
    contact_text = Contact.objects.all()
    seo = SEO.objects.filter(tag="contact")
    og = OG.objects.filter(tag="contact")
    return render(request, "contact.html", {
        "contact_text": contact_text, 
        "seo": seo,
        "og": og
    })


def single_employee(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    seo = SEO.objects.filter(tag="single_employee")
    og = OG.objects.filter(tag="single_employee")
    return render(request, "single_employee.html", {
        "employee": employee,
        "seo": seo,
        "og": og
    })


def single_member(request, member_id):
    member = Team.objects.get(pk=member_id)
    seo = SEO.objects.filter(tag="single_member")
    og = OG.objects.filter(tag="about")
    return render(request, "single_member.html", {
        "member": member,
        "seo" : seo,
        "og": og
    })

@require_POST
def change_lang(request):
    language = request.POST.get("language")
    if language:
        activate(language)
        request.session[translation.LANGUAGE_SESSION_KEY] = language
        return JsonResponse({"success": True, "language": get_language()})
    return JsonResponse({"success": False})

employees/templates/about.html
{% extends "base.html" %}
   
{% block seo_block %}
  {% for item in seo %}
  <title> {{item.title}} </title>
  <meta name="title" content="{{item.title}}">
  <meta name="description" content="{{item.description}}">
  <meta name="keywords" content="{{item.keywords}}">
  <meta name="robots" content="{{item.robots}}">
  <meta http-equiv="Content-Type" content="{{item.content_type}}">
  <meta name="language" content="{{item.language}}">
  {% endfor %}
{% endblock %}

{% block og_block %}
  {% for item in og %}
    <meta property="og:title" content="{{item.title}}" />
    <meta property="og:type" content="{{item.type}}" />
    <meta property="og:url" content="{{item.url}}" />
    <meta property="og:image" content="{{item.image.url}}" />
    <meta property="og:description" content="{{item.description}}" />
  {% endfor %}
{% endblock %}

{% block about_template %}  
    <div class="mt-5">
        <h1>About Us</h1> 
        <article>
            {% for about in about_text %}
                <h1>{{ about.title }}</h1>
                <p>{{ about.body }}</p>
            {% endfor %}
        </article>
        <h2 class="mt-4 mb-4">Our Team</h2>
        <div style="
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
          grid-gap: 16px;  
        ">
          {% for member in team %}
            <div class="card">
                <div class="card-header">
                    <div>
                      <img class="img-thumbnail" src="{{ member.avatar.url }}" alt="{{ member.position }}">
                    </div>
                    <h3 class="text-center mt-2 mb-2">{{member.first_name}}{{member.last_name}}</h3>
                </div>
                <div class="card-body">
                    <h4>{{member.position}}</h4>
                    <p>{{member.about}}</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'app:single_member' member.id %}" class="btn btn-success d-block">Read More</a> 
                </div>
            </div>
          {% endfor %}
        </div>
    </div>     
{% endblock %}

        
        {% comment %} <div class="mt-3">
            <div class="card">
                <div class="card-header">
                    <img src="" alt="">
                    <h3>Jack Marton</h3>
                </div>
                <div class="card-body">
                    <h4>Project Owner</h4>  
                    <p>About Beautiful Armenia</p>
                </div>
                <div class="card-footer">
                    <a href="" class="btn btn-success d-block">Read More</a> 
                </div>
            </div>
        </div>
    </div>     
{% endblock %}  {% endcomment %}

employees/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block seo_block %}{% endblock %}
    {% block og_block %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="stylesheet" href={% static "css/styles.css" %}>
  </head> 
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container w-100">
        <a href="{% url 'app:index' %}"class="navbar-brand">
          <img 
          src={% static "img/logo.png" %} 
          alt="logo"
          class="img-fluid"
          style="width: 200px; height: 100px;"
          >
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mobileMenu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse gap-4" id="mobileMenu">
          <ul class="navbar-nav w-100 justify-content-end gap-3">
            <li class="nav-item">
              <a href="{% url 'app:employees' %}" style="color: #16bc5c" class="text-hover fs-5 text-decoration-none">{% trans "Employees"%}</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'app:about' %}" style="color: #16bc5c" class="text-hover fs-5 text-decoration-none">{% trans "About" %}</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'app:contact' %}" style="color: #16bc5c" class="text-hover fs-5 text-decoration-none">{% trans "Contact" %}</a>
            </li>
            <li class="nav-item">
              <a href="/admin" target="_blank" style="color:#16bc5c" class="text-hover text-hover fs-5 text-decoration-none">{% trans "Admin Panel" %}</a>
            </li>
            <li class="nav-item">
              <a href="/api/v1/" target="_blank" style="color:#16bc5c" class=" text-hover fs-5 text-decoration-none">Api</a>
            </li>
          </ul>
          <div class="d-flex gap-2">
            <form id="language-form" action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input type="hidden" id="language-input" name="language">
            </form>
  
            {% for l in LANGUAGES %}
                <button class="language-button btn btn-sm btn-info text-white" value="{{ l.0 }}">{{ l.1 }}</button>
            {% endfor %}
          </div>
        </div>
      </div>
    </nav>
    <main class="container">           
      {% block home_template %}{% endblock %}
      {% block employees_template %}{% endblock %}
      {% block single_employee_template %}{% endblock %} 
      {% block single_team_template %}{% endblock %}
      {% block about_template %}{% endblock %}
      {% block contact_template %}{% endblock %}
    </main>
    <footer>
      <div class="container">
        {% trans "All Rights Reserved" %} & copy; 2024
      </div>  
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script src={% static "js/script.js" %}></script>
  </body>
</html>    

employees/templates/contact.html
{% extends 'base.html' %}

{% block seo_block %}
  {% for item in seo %}
  <title> {{item.title}} </title>
  <meta name="title" content="{{item.title}}">
  <meta name="description" content="{{item.description}}">
  <meta name="keywords" content="{{item.keywords}}">
  <meta name="robots" content="{{item.robots}}">
  <meta http-equiv="Content-Type" content="{{item.content_type}}">
  <meta name="language" content="{{item.language}}">
  {% endfor %}
{% endblock %}

{% block og_block %}
  {% for item in og %}
    <meta property="og:title" content="{{item.title}}" />
    <meta property="og:type" content="{{item.type}}" />
    <meta property="og:url" content="{{item.url}}" />
    <meta property="og:image" content="{{item.image.url}}" />
    <meta property="og:description" content="{{item.description}}" />
  {% endfor %}
{% endblock %}

{% block contact_template %}  
    <div class="mt-5">
        <h1>Contact</h1>
        <div>
            {% for contact in contact_text %}
                <p>Address: {{ contact.address }}</p>
                <p>Email: {{ contact.email }}</p>
                <p>Phone: {{ contact.phone }}</p>
            {% endfor %}
        </div>
    </div>     
{% endblock %}

employees/templates/employees.html
{% extends "base.html" %}

{% block seo_block %}
  {% for item in seo %}
  <title> {{item.title}} </title>
  <meta name="title" content="{{item.title}}">
  <meta name="description" content="{{item.description}}">
  <meta name="keywords" content="{{item.keywords}}">
  <meta name="robots" content="{{item.robots}}">
  <meta http-equiv="Content-Type" content="{{item.content_type}}">
  <meta name="language" content="{{item.language}}">
  {% endfor %}
{% endblock %}

{% block og_block %}
  {% for item in og %}
    <meta property="og:title" content="{{item.title}}" />
    <meta property="og:type" content="{{item.type}}" />
    <meta property="og:url" content="{{item.url}}" />
    <meta property="og:image" content="{{item.image.url}}" />
    <meta property="og:description" content="{{item.description}}" />
  {% endfor %}
{% endblock %}

{% block employees_template %} 
    <div class="table-responsive mt-5">
    <table class="table table-hover table-bordered table-primary">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>FIRSTNAME</th>
                <th>LASTNAME</th>
                <th>EMAIL</th>
                <th>IS MARRIED</th>
                <th>SALLARY</th>
                <th>DEPARTMENT</th>
                <th>CONTACT EXP</th>
                <th>INFO</th>   
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>
                <th>{{ employee.id }}</th>
                <td>{{ employee.first_name }}</td>
                <td>{{ employee.last_name }}</td>
                <td>{{ employee.email }}</td>
                <td>{{ employee.is_married }}</td>
                <td>{{ employee.salary }}</td>
                <td>{{ employee.department }}</td>
                <td>{{ employee.contract_exp }}</td>
                <td>
                    <a href="{% url 'app:single_employee' employee.id %}">See More</a>
                </td>
            </tr>
            {% endfor %}
        </tbody> 
    </table> 
    </div>
{% endblock %}

employees/templates/home.html
{% extends "base.html" %}
{% load i18n %}
  
{% block seo_block %}
  {% for item in seo %}
    <title> {{item.title}} </title>
    <meta name="title" content="{{item.title}}">
    <meta name="description" content="{{item.description}}">
    <meta name="keywords" content="{{item.keywords}}">
    <meta name="robots" content="{{item.robots}}">
    <meta http-equiv="Content-Type" content="{{item.content_type}}">
    <meta name="language" content="{{item.language}}">
  {% endfor %}
{% endblock %}

{% block og_block %}
  {% for item in og %}
    <meta property="og:title" content="{{item.title}}" />
    <meta property="og:type" content="{{item.type}}" />
    <meta property="og:url" content="{{item.url}}" />
    <meta property="og:image" content="{{item.image.url}}" />
    <meta property="og:description" content="{{item.description}}" />
  {% endfor %}
{% endblock %}

{% block home_template %}  
  <div class="mt-5 text-center">
      <h1>{% trans "Welcome to our website" %}</h1>
      <p>{% trans "This is our official website" %}</p>
  </div>     
  <div class="mt-5">
    <div class="swiper mySwiper">
      <div class="swiper-wrapper">
        {% for slide in slides %}
        <div class="swiper-slide position-static">
          <div 
            class="slider-conten position-absolute p-5"
            style="
              max-width: 300px;
              background: rgba(0, 0, 0, 0.8);
              color: #fff;
              top: 50px;
              left: 30px;
            "
          >
            <h3>{{slide.title}}</h3>
            <p>{{slide.descr}}</p>
            {% if slide.link %}
              <a class="btn btn-success" href="{{slide.link}}">Read More</a>
            {% endif %}
          </div>
          <img src="{{slide.img.url}}" alt="{{slide.title}}">
        </div>
      {% endfor %} 
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
  </div> 
  </div>
{% endblock %} 

employees/templates/single-employee.html
{% extends "base.html" %}

{% block title %}
    About {{ employee.first_name }} {{ employee.last_name }}
{% endblock %}  

{% block single_employee_template %}  
    <div class="mt-5">
        <div class="card-header">
            <h1>{{ employee.first_name }} {{ employee.last_name }}</h1>
        </div>
        <div class="card-body">
            <h4>Email: {{ employee.email }}</h4>
            <h5>Is Married: {{ employee.is_married }}</h5>
            <h5>Salary: {{ employee.salary }}</h5>
            <h5>Contact: {{ employee.contract_exp }}</h5>
            <h5>Department: {{ employee.department }}</h5>
        </div>    
    </div>     
{% endblock %}

employees/templates/single_employee.html
{% extends "base.html" %}

{% block seo_block %}
  {% for item in seo %}
  <title> About {{ employee.first_name }} {{ employee.last_name }} | {{item.title}} </title>
  <meta name="title" content="About {{ employee.first_name }} {{ employee.last_name }} | {{item.title}}">
  <meta name="description" content="{{item.description}}">
  <meta name="keywords" content="{{item.keywords}}">
  <meta name="robots" content="{{item.robots}}">
  <meta http-equiv="Content-Type" content="{{item.content_type}}">
  <meta name="language" content="{{item.language}}">
  {% endfor %}
{% endblock %}

{% block og_block %}
  {% for item in og %}
    <meta property="og:title" content="{{item.title}}" />
    <meta property="og:type" content="{{item.type}}{{employee.id}}" />
    <meta property="og:url" content="{{item.url}}{{employee.id}}" />
    <meta property="og:image" content="{{item.image.url}}" />
    <meta property="og:description" content="{{item.description}}" />
  {% endfor %}
{% endblock %}

{% block single_employee_template %}  
    <div class="card mt-5">
        <div class="card-header">
            <h1>{{ employee.first_name }} {{ employee.last_name }}</h1>
        </div>
        <div class="card-body">
            <h4>Email: {{ employee.email }}</h4>
            <h5>Is Married: {{ employee.is_married }}</h5>
            <h5>Salary: {{ employee.salary }}</h5>
            <h5>Contact: {{ employee.contract_exp }}</h5>
            <h5>Department: {{ employee.department }}</h5>
        </div>    
    </div>     
{% endblock %}

employees/templates/single_member.html
{% extends 'base.html' %}

{% block seo_block %}
  {% for item in seo %}
  <title> About {{member.first_name }} {{ member.last_name }} | {{item.title}} </title>
  <meta name="title" content= "About {{member.first_name }} {{ member.last_name }} | {{item.title}}">
  <meta name="description" content="{{item.description}}">
  <meta name="keywords" content="{{item.keywords}}">
  <meta name="robots" content="{{item.robots}}">
  <meta http-equiv="Content-Type" content="{{item.content_type}}">
  <meta name="language" content="{{item.language}}">
  {% endfor %}
{% endblock %} 

{% block og_block %}
  {% for item in og %}
    <meta property="og:title" content="{{item.title}}" />
    <meta property="og:type" content="{{item.type}}{{member.id}}" />
    <meta property="og:url" content="{{item.url}}{{member.id}}" />
    <meta property="og:image" content="{{item.image.url}}" />
    <meta property="og:description" content="{{item.description}}" />
  {% endfor %}
{% endblock %}

{% block single_team_template %}  
    <div class="card mt-5">
        <div class="card-header">
            <h1>{{ member.first_name }} {{ member.last_name }}</h1>
        </div>
        <div class="card-body">
            <img class="img-thumbnail" src="{{member.avatar.url}}" alt="{{member.first_name}}">
            <h4>Position: {{ member.position }}</h4>
            <h4>About: {{ member.about }}</h4>
        </div>    
    </div>     
{% endblock %}